// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Setup',
      items: ['Setup/installation', 'Setup/server-settings', 'Setup/worlds', 'Setup/arenas', 'Setup/signs'],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: ['Configuration/overview', 'Configuration/settings'],
    },
    {
      type: 'category',
      label: 'Languages',
      items: ['Languages/overview', 'Languages/ar-sa', 'Languages/en-us', 'Languages/es-es', 'Languages/fr-fr', "Languages/ru-ru", "Languages/zh-cn"],
    },
    {
      type: 'category',
      label: 'References',
      items: ['References/editing-configs', 'References/commands', 'References/placeholders'],
    },
  ],
};

export default sidebars;
